name: CI
on:
  workflow_dispatch:
    inputs:
        bump-type:
          description: "Semantic versioning / Bump type [major, feature, bug, beta]"
          required: true
          default: 'beta'

jobs:
  prepare-build:
    runs-on: ubuntu-latest
    continue-on-error: false
    outputs:
      version: ${{steps.version-resolver.outputs.value}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: currentBranch

      - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Bump release version
        id: sem-version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.previoustag.outputs.tag }}
          version-fragment: ${{ github.event.inputs.bump-type }}

      - name: Increase pom version
        run: |
          mvn versions:set  -DgroupId=juanignacionogueira.tests -DartifactId=test-actions -DnewVersion=${{steps.sem-version.outputs.next-version}} -DgenerateBackupPoms=false -DprocessDependencies=false -DprocessPlugins=false -DprocessParent=false
          git config --global user.name "Juan"
          git config --global user.email "juanignacionogueira@gmail.com"
          git commit -a -m "Increase pom version ${{steps.sem-version.outputs.next-version}}"

      - name: Create tag
        run: |
          git tag -a ${{steps.sem-version.outputs.next-version}} -m "Nueva versión ${{steps.sem-version.outputs.next-version}}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: update-pull-request
        uses: kt3k/update-pr-description@v1.0.0
        with:
          pr_title: "TEST"
          destination_branch: "main"
          github_token: ${{secrets.GITHUB_TOKEN}}

  update-status:
    needs: [ prepare-build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set status
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'some-check'
          state: 'success'
